<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.dromara</groupId>
        <artifactId>ruoyi-vue-plus</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ruoyi-admin</artifactId>
    <packaging>pom</packaging>

    <name>ruoyi-admin</name>
    <description>Admin 后台管理总工程</description>

    <modules>
        <module>ruoyi-admin-api</module>
        <module>ruoyi-admin-server</module>
        <module>../ruoyi-modules/ruoyi-system</module>
        <module>../ruoyi-modules/ruoyi-gen</module>
        <module>../ruoyi-modules/ruoyi-job</module>
        <module>../ruoyi-modules/ruoyi-workflow</module>
        <module>../ruoyi-modules/ruoyi-ai</module>
        <module>../ruoyi-modules/ruoyi-demo</module>
    </modules>

</project>
