<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara</groupId>
        <artifactId>ruoyi-vue-plus</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>ruoyi-applications</artifactId>
    <packaging>pom</packaging>
    <description>Admin 管理用例与 Client 用户用例编排</description>
    <modules>
        <module>ruoyi-admin-application</module>
        <module>ruoyi-client-application</module>
    </modules>
</project>
